services:
  samba:
    image: dperson/samba
    container_name: samba_prueba
    restart: unless-stopped
    network_mode: host
    volumes:
      - /datos/proyectos:/shared:rw
    environment:
      - USER=invitado;prueba123
      - USER=invitado1;1234
      - USER=invitado2;patito23
      - USER=Target;Mike_Godinez
      - SHARE=proyectos;/shared;yes;no;no;Invitado,invitado1,invitado2,Target
